# Generated by Django 4.0.4 on 2022-06-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='redimento',
            new_name='rendimento',
        ),
    ]
